# Generated by Django 4.2.7 on 2023-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('house_type', models.CharField(max_length=75)),
                ('image', models.ImageField(default='defaulthouse.jpg', null=True, upload_to='')),
            ],
        ),
    ]
